name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: playacrcicd.azurecr.io
          username: ${{ secrets.AZURE_CREDENTIALS_USERNAME }}
          password: ${{ secrets.AZURE_CREDENTIALS_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t playacrcicd.azurecr.io/fastapi-cicd:${{ github.sha }} .
          docker push playacrcicd.azurecr.io/fastapi-cicd:${{ github.sha }}

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: fastapicicdwebapp
          images: 'playacrcicd.azurecr.io/fastapi-cicd:${{ github.sha }}'
